Migrate club preferences to db (#11)
* fix CI

* eliminate the need for default value
error if the club not found during the query

* clean up, add createdAt in reservation schema

* migrated club open / close time preferences to db

* change pscale action version

* accept data loss when prisma db push

* split DR check

* remove echo

* explicit exit 0 when stderr redirect

* add "|| true" at the end of failing command

* fix logic on DR already existing

* remove maxReservation constant
refactor date in reservation dialog
reservation mutation takes clubId
refactor for clubId is no more optional
remove example schema

* Add FullCalendarWrapper component testing
Reorganize e2e test in categories
logout using session (no relogin needed)
hourBeforeCancel moved to db
check for reservation query error in calendar

* enhanced tests for different closing minute cases
Comp test for reservation end time beyond closing time
Better error message on end time validation
ReserveDialog.tsx enhance

* remove db dependencies from component test

* allowing import of module in cypress (@fullcalendar)
EventDetailDialog component test
add Reservation detail e2e test section
prevent user from opening reservation detail of other users

* Well defined user and admin for cypress testing
Seed the db with two clubs and an admin
fix AT: delete other member reservation

* AT: can delete only N hours before start

* clean up

* AT no contamination of reservation among clubs

* starting admin component testing

* retrigger sonarcube

diff --git a/.github/workflows/planetscale-open-dr.yml b/.github/workflows/planetscale-open-dr.yml
--- a/.github/workflows/planetscale-open-dr.yml
+++ b/.github/workflows/planetscale-open-dr.yml
@@ -25,7 +25,7 @@ jobs:
       - name: Setup pscale
         uses: planetscale/setup-pscale-action@v1
       - name: Create a branch
-        uses: planetscale/create-branch-action@v4
+        uses: planetscale/create-branch-action@v3
         id: create_branch
         with:
           org_name: ${{ secrets.PLANETSCALE_ORG_NAME }}
@@ -38,7 +38,7 @@ jobs:
         run: |
           pscale connect ${{secrets.PLANETSCALE_DATABASE_NAME}} ${{ env.PSCALE_BRANCH_NAME }} --port 3309 --org ${{ secrets.PLANETSCALE_ORG_NAME }} &
           sleep 10
-          npx prisma db push --skip-generate > migration-output.txt
+          npx prisma db push --skip-generate --accept-data-loss > migration-output.txt
           kill %1
           if grep -q "Your database is now in sync with your Prisma schema" migration-output.txt; then
             echo "DB_MIGRATED=true" >> $GITHUB_ENV;
@@ -52,21 +52,26 @@ jobs:
           echo "Did not open a DR since no changes found"
           echo "> 'prisma db push' output:\n"
           cat migration-output.txt
-          exit 0
 
-      - name: Close existing DR if any
+      - name: Check for already open DR
         if: ${{ env.DB_MIGRATED }}
+        # || true to avoid failing the job if the DR does not exist (redirect to stderr is not enough to prevent failure exit)
         run: |
-          pscale deploy-request show ${{ secrets.PLANETSCALE_DATABASE_NAME }} ${{ env.PSCALE_BRANCH_NAME }} -f json --org ${{ secrets.PLANETSCALE_ORG_NAME }} 2> check_dr_stderr.txt
+          pscale deploy-request show ${{ secrets.PLANETSCALE_DATABASE_NAME }} ${{ env.PSCALE_BRANCH_NAME }} -f json --org ${{ secrets.PLANETSCALE_ORG_NAME }} 2> check_dr_stderr.txt  || true 
           if grep -q "error" check_dr_stderr.txt; then
-            echo "Not found any DR to close";
+            echo "No DR found"
           else
-            echo "DR found, closing it before proceeding";
-            deploy_request_number=$(pscale deploy-request show ${{ secrets.PLANETSCALE_DATABASE_NAME }} ${{ env.PSCALE_BRANCH_NAME }} -f json --org ${{ secrets.PLANETSCALE_ORG_NAME }} | jq -r '.number')
-            pscale deploy-request close ${{ secrets.PLANETSCALE_DATABASE_NAME }} $deploy_request_number --org ${{ secrets.PLANETSCALE_ORG_NAME }};
+            echo "DR_ALREADY_EXISTS=true" >> $GITHUB_ENV
           fi
 
-      - name: Open DR if migrations
+      - name: close already existing DR
+        if: ${{ env.DR_ALREADY_EXISTS }}
+        run: |
+          echo "DR found, closing it before proceeding";
+          deploy_request_number=$(pscale deploy-request show ${{ secrets.PLANETSCALE_DATABASE_NAME }} ${{ env.PSCALE_BRANCH_NAME }} -f json --org ${{ secrets.PLANETSCALE_ORG_NAME }} | jq -r '.number')
+          pscale deploy-request close ${{ secrets.PLANETSCALE_DATABASE_NAME }} $deploy_request_number --org ${{ secrets.PLANETSCALE_ORG_NAME }};
+
+      - name: Open new DR
         if: ${{ env.DB_MIGRATED }}
         run: |
           if pscale deploy-request create ${{ secrets.PLANETSCALE_DATABASE_NAME }} ${{ env.PSCALE_BRANCH_NAME }} --org ${{ secrets.PLANETSCALE_ORG_NAME }}; then
