deploy preview workflow and delete db branch [skip ci]

diff --git a/.github/workflows/vercel-deploy-from-pr.yml b/.github/workflows/vercel-deploy-from-pr.yml
--- a/.github/workflows/vercel-deploy-from-pr.yml
+++ b/.github/workflows/vercel-deploy-from-pr.yml
@@ -9,6 +9,7 @@ env:
   PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
+  DEPLOY_SUCCESS_STATUS: "complete"
 jobs:
   deploy-db:
     if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
@@ -28,6 +29,22 @@ jobs:
         if: ${{ env.DEPLOY_REQUEST_NUMBER }}
         run: |
           pscale deploy-request deploy ${{ secrets.PLANETSCALE_DATABASE_NAME }} ${{ env.DEPLOY_REQUEST_NUMBER }} --org ${{ secrets.PLANETSCALE_ORG_NAME }} --wait
+      - name: Check deploy result
+        if: ${{ env.DEPLOY_REQUEST_NUMBER }}
+        run: |
+          deploy_request_status=$(pscale deploy-request show ${{ secrets.PLANETSCALE_DATABASE_NAME }} ${{ env.DEPLOY_REQUEST_NUMBER }} --org ${{ secrets.PLANETSCALE_ORG_NAME }} -f json | jq -r '.deployment.state')
+          if [ "$deploy_request_status" == "${{env.DEPLOY_SUCCESS_STATUS}}" ]; then
+            echo "Deployed successfully"
+            echo "DEPLOY_SUCCESS=true" >> $GITHUB_ENV;
+            exit 0
+          else
+            echo "Deployment failed"
+            exit 1
+          fi
+      - name: Delete db branch
+        if: ${{env.DEPLOY_SUCCESS}}
+        run: |
+          pscale branch delete ${{ secrets.PLANETSCALE_DATABASE_NAME }} ${{ env.PSCALE_BRANCH_NAME }} --org ${{ secrets.PLANETSCALE_ORG_NAME }} --force
 
   deploy-code:
     runs-on: ubuntu-latest
